FROM node:16-alpine

WORKDIR /var/www/app

# install global packages
RUN apk update \
    && apk upgrade \
    && apk add --no-cache  \
    yarn

# install frontend packages
COPY package.json package.json
COPY yarn.lock yarn.lock
RUN set -ex && yarn

COPY . .

RUN yarn build
